
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Navbar from "@/custom-components/Navbar";
import TanstackProvider from "@/utils/TanstackProvider";
import AddFileButton from "@/custom-components/AddFileButton";
import Searchbar from "@/custom-components/Searchbar";
import Footer from "@/custom-components/Footer";
import { Toaster } from "@/components/ui/toaster";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon:'/martizine.png'
  }
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId={process.env.GOOGE_OAUTH_CLIENT_ID??""}>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100`}
      >
        <TanstackProvider>
          <Toaster />
        <div>
        <Navbar />
        {/* <div className="h-full px-4 sm:px-6 md:px-8">
      <div className="flex gap-2 w-full items-center">
       <AddFileButton />
       <Searchbar />
      </div>
        </div> */}
          {children}
        </div>
        </TanstackProvider>
      </body>
    </html>
    </GoogleOAuthProvider>
  );
}
