
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Navbar from "@/custom-components/Navbar";
import {QueryClient, QueryClientProvider} from '@tanstack/react-query'
import TanstackProvider from "@/utils/TanstackProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon:'/martizine.png'
  }
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId={process.env.GOOGE_OAUTH_CLIENT_ID??""}>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100`}
      >
        <TanstackProvider>
        <div>
        <Navbar />
          {children}
        </div>
        </TanstackProvider>
      </body>
    </html>
    </GoogleOAuthProvider>
  );
}
